import type { IAlertData } from '@/interfaces/alert/alert-table';

export const AlertDataSample: IAlertData[] = [
    {
        id: 'alert001',
        type: 'task',
        name: 'DataImportTask',
        description: 'Task for importing user data completed',
        statusCode: 200,
        status: 'Success',
        createdAt: '2025-05-26T00:55:00Z',
    },
    {
        id: 'alert002',
        type: 'workflow',
        name: 'UserOnboardingFlow',
        description: 'Workflow for user onboarding failed due to missing fields',
        statusCode: 400,
        status: 'Failed',
        createdAt: '2025-05-26T00:30:00Z',
    },
    {
        id: 'alert003',
        type: 'task',
        name: 'ReportGenerationTask',
        description: 'Task for generating report timed out',
        statusCode: 408,
        status: 'Timeout',
        createdAt: '2025-05-25T23:45:00Z',
    },
    {
        id: 'alert004',
        type: 'workflow',
        name: 'PaymentProcessingFlow',
        description: 'Workflow for payment processing completed successfully',
        statusCode: 200,
        status: 'Success',
        createdAt: '2025-05-25T23:00:00Z',
    },
    {
        id: 'alert005',
        type: 'task',
        name: 'EmailNotificationTask',
        description: 'Task for sending email notifications failed',
        statusCode: 500,
        status: 'Failed',
        createdAt: '2025-05-25T22:15:00Z',
    },
    {
        id: 'alert006',
        type: 'workflow',
        name: 'DataSyncFlow',
        description: 'Workflow for data synchronization timed out',
        statusCode: 408,
        status: 'Timeout',
        createdAt: '2025-05-25T21:30:00Z',
    },
    {
        id: 'alert007',
        type: 'task',
        name: 'CacheRefreshTask',
        description: 'Task for refreshing cache completed',
        statusCode: 200,
        status: 'Success',
        createdAt: '2025-05-25T20:45:00Z',
    },
    {
        id: 'alert008',
        type: 'workflow',
        name: 'SecurityAuditFlow',
        description: 'Workflow for security audit failed at validation',
        statusCode: 500,
        status: 'Failed',
        createdAt: '2025-05-25T20:00:00Z',
    },
    {
        id: 'alert009',
        type: 'task',
        name: 'UserProfileUpdateTask',
        description: 'Task for updating user profiles succeeded',
        statusCode: 200,
        status: 'Success',
        createdAt: '2025-05-25T19:15:00Z',
    },
    {
        id: 'alert010',
        type: 'workflow',
        name: 'SystemUpgradeFlow',
        description: 'Workflow for system upgrade deployed successfully',
        statusCode: 200,
        status: 'Success',
        createdAt: '2025-05-25T18:30:00Z',
    },
];
