import type { IAuditlogData } from '@/interfaces/log/auditlog-table';

export const AuditLogDataSample: IAuditlogData[] = [
    {
        id: 'log1',
        userId: 'user123',
        useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/91.0.4472.124',
        ip: '192.168.1.1',
        resource: '/users/profile',
        method: 'POST',
        api: 'GET /api/v1/users',
        body: {
            username: 'sad',
            password: 'sda',
            age: 1,
            gender: 'Male',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log2',
        userId: 'user456',
        useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1.15',
        ip: '172.16.0.2',
        resource: '/settings',
        method: 'POST',
        api: 'PUT /api/v1/settings',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log3',
        userId: 'user789',
        useragent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_6) Mobile/15E148',
        ip: '10.0.0.3',
        resource: '/dashboard',
        method: 'POST',
        api: 'POST /api/v1/dashboard',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log4',
        userId: 'user101',
        useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/89.0',
        ip: '192.168.1.4',
        resource: '/orders',
        method: 'POST',
        api: 'GET /api/v1/orders',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log5',
        userId: 'user202',
        useragent: 'Mozilla/5.0 (Linux; Android 11) Chrome/90.0.4430.85',
        ip: '172.16.0.5',
        resource: '/products',
        method: 'POST',
        api: 'GET /api/v1/products',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log6',
        userId: 'user303',
        useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) Chrome/89.0.4389.82',
        ip: '10.0.0.6',
        resource: '/cart',
        method: 'POST',
        api: 'POST /api/v1/cart',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log7',
        userId: 'user404',
        useragent: 'Mozilla/5.0 (iPad; CPU OS 14_5) Safari/604.1',
        ip: '192.168.1.7',
        resource: '/payment',
        method: 'POST',
        api: 'POST /api/v1/payment',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log8',
        userId: 'user505',
        useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/91.0.864.48',
        ip: '172.16.0.8',
        resource: '/account',
        method: 'POST',
        api: 'PUT /api/v1/account',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log9',
        userId: 'user606',
        useragent: 'Mozilla/5.0 (Linux; Android 10) Chrome/88.0.4324.181',
        ip: '10.0.0.9',
        resource: '/wishlist',
        method: 'POST',
        api: 'GET /api/v1/wishlist',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log10',
        userId: 'user707',
        useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) Firefox/88.0',
        ip: '192.168.1.10',
        resource: '/notifications',
        method: 'POST',
        api: 'GET /api/v1/notifications',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log9',
        userId: 'user606',
        useragent: 'Mozilla/5.0 (Linux; Android 10) Chrome/88.0.4324.181',
        ip: '10.0.0.9',
        resource: '/wishlist',
        method: 'POST',
        api: 'GET /api/v1/wishlist',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log10',
        userId: 'user707',
        useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) Firefox/88.0',
        ip: '192.168.1.10',
        resource: '/notifications',
        method: 'POST',
        api: 'GET /api/v1/notifications',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log9',
        userId: 'user606',
        useragent: 'Mozilla/5.0 (Linux; Android 10) Chrome/88.0.4324.181',
        ip: '10.0.0.9',
        resource: '/wishlist',
        method: 'POST',
        api: 'GET /api/v1/wishlist',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
    {
        id: 'log10',
        userId: 'user707',
        useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) Firefox/88.0',
        ip: '192.168.1.10',
        resource: '/notifications',
        method: 'POST',
        api: 'GET /api/v1/notifications',
        body: {
            username: 'sad',
            password: 'sda',
        },
        createdAt: '2025-05-25T02:19:00Z',
    },
];
