import type { IRoleData } from '@/interfaces/role-table';

export const RoleDataSample: IRoleData[] = [
    {
        id: 'role_001',
        name: 'Admin',
        status: 'success',
        logPolicy: ['view_all', 'edit_logs'],
        dashboardPolicy: ['full_access'],
        logViewPolicy: ['all_logs'],
        workflowPolicy: ['create_workflow', 'edit_workflow'],
        alertPolicy: ['view_alerts', 'manage_alerts'],
        taskPolicy: ['assign_tasks', 'delete_tasks'],
        createdAt: '2025-01-15T10:00:00Z',
        updatedAt: '2025-05-20T14:30:00Z',
    },
    {
        id: 'role_002',
        name: 'Editor',
        status: 'processing',
        logPolicy: ['view_logs'],
        dashboardPolicy: ['view_dashboard'],
        logViewPolicy: ['team_logs'],
        workflowPolicy: ['edit_workflow'],
        alertPolicy: ['view_alerts'],
        taskPolicy: ['assign_tasks'],
        createdAt: '2025-02-10T09:15:00Z',
        updatedAt: '2025-05-25T08:45:00Z',
    },
    {
        id: 'role_003',
        name: 'Viewer',
        status: 'pending',
        logPolicy: ['view_logs'],
        dashboardPolicy: ['view_dashboard'],
        logViewPolicy: ['public_logs'],
        workflowPolicy: [],
        alertPolicy: ['view_alerts'],
        taskPolicy: [],
        createdAt: '2025-03-05T12:20:00Z',
        updatedAt: '2025-05-26T16:10:00Z',
    },
    {
        id: 'role_004',
        name: 'Manager',
        status: 'success',
        logPolicy: ['view_all', 'edit_logs'],
        dashboardPolicy: ['full_access'],
        logViewPolicy: ['all_logs'],
        workflowPolicy: ['create_workflow', 'approve_workflow'],
        alertPolicy: ['manage_alerts'],
        taskPolicy: ['assign_tasks', 'review_tasks'],
        createdAt: '2025-04-01T11:30:00Z',
        updatedAt: '2025-05-27T06:00:00Z',
    },
    {
        id: 'role_005',
        name: 'Analyst',
        status: 'failed',
        logPolicy: ['view_logs'],
        dashboardPolicy: ['view_dashboard'],
        logViewPolicy: ['team_logs'],
        workflowPolicy: ['view_workflow'],
        alertPolicy: ['view_alerts'],
        taskPolicy: ['view_tasks'],
        createdAt: '2025-04-20T15:45:00Z',
        updatedAt: '2025-05-25T10:20:00Z',
    },
    {
        id: 'role_006',
        name: 'Guest',
        status: 'pending',
        logPolicy: [],
        dashboardPolicy: ['view_dashboard'],
        logViewPolicy: ['public_logs'],
        workflowPolicy: [],
        alertPolicy: [],
        taskPolicy: [],
        createdAt: '2025-05-10T08:00:00Z',
        updatedAt: '2025-05-27T07:00:00Z',
    },
];
