import type { ITaskRecord } from '@/interfaces/task/task-table';

export const TaskRecordSample: ITaskRecord[] = [
    {
        id: 'task1',
        status: 'Running',
        name: 'WebMonitor',
        type: 'HTTP',
        description: 'Monitors website uptime',
        target: 'https://api.example.com',
        interval: 300,
        numOfRetry: 3,
        createdAt: '2025-06-03T13:00:00Z',
        updatedAt: '2025-06-03T13:10:00Z',
    },
    {
        id: 'task2',
        status: 'Stopped',
        name: 'BackupScript',
        type: 'Shell',
        description: 'Runs nightly backup',
        target: '/scripts/backup.sh',
        interval: 86400,
        numOfRetry: 2,
        createdAt: '2025-06-03T12:00:00Z',
        updatedAt: '2025-06-03T12:30:00Z',
    },
    {
        id: 'task3',
        status: 'Created',
        name: 'DataSync',
        type: 'Remote Shell',
        description: 'Syncs data to remote server',
        target: 'user@remote:/data',
        interval: 3600,
        numOfRetry: 5,
        createdAt: '2025-06-03T13:15:00Z',
        updatedAt: '2025-06-03T13:15:00Z',
    },
    {
        id: 'task4',
        status: 'Restarting',
        name: 'MLTraining',
        type: 'Python',
        description: 'Trains ML model',
        target: '/scripts/train.py',
        interval: 7200,
        numOfRetry: 1,
        createdAt: '2025-06-03T10:00:00Z',
        updatedAt: '2025-06-03T13:20:00Z',
    },
    {
        id: 'task5',
        status: 'Running',
        name: 'HealthCheck',
        type: 'HTTP',
        description: 'Checks API health',
        target: 'https://health.example.com',
        interval: 600,
        numOfRetry: 3,
        createdAt: '2025-06-03T11:00:00Z',
        updatedAt: '2025-06-03T13:25:00Z',
    },
    {
        id: 'task6',
        status: 'Deleting',
        name: 'OldScript',
        type: 'Shell',
        description: 'Deprecated cleanup script',
        target: '/scripts/cleanup.sh',
        interval: 43200,
        numOfRetry: 0,
        createdAt: '2025-06-02T09:00:00Z',
        updatedAt: '2025-06-03T13:30:00Z',
    },
    {
        id: 'task7',
        status: 'Stopped',
        name: 'LogParser',
        type: 'Python',
        description: 'Parses server logs',
        target: '/scripts/log_parser.py',
        interval: 1800,
        numOfRetry: 2,
        createdAt: '2025-06-03T08:00:00Z',
        updatedAt: '2025-06-03T13:35:00Z',
    },
    {
        id: 'task8',
        status: 'Running',
        name: 'RemoteBackup',
        type: 'Remote Shell',
        description: 'Backs up to remote server',
        target: 'user@backup:/backup',
        interval: 86400,
        numOfRetry: 4,
        createdAt: '2025-06-03T07:00:00Z',
        updatedAt: '2025-06-03T13:40:00Z',
    },
    {
        id: 'task9',
        status: 'Created',
        name: 'StatusCheck',
        type: 'HTTP',
        description: 'Checks service status',
        target: 'https://status.example.com',
        interval: 1200,
        numOfRetry: 3,
        createdAt: '2025-06-03T13:45:00Z',
        updatedAt: '2025-06-03T13:45:00Z',
    },
    {
        id: 'task10',
        status: 'Restarting',
        name: 'DataProcessor',
        type: 'Python',
        description: 'Processes incoming data',
        target: '/scripts/processor.py',
        interval: 3600,
        numOfRetry: 2,
        createdAt: '2025-06-03T09:30:00Z',
        updatedAt: '2025-06-03T13:50:00Z',
    },
];
