import type { IUserData } from '@/interfaces/user-table';

export const UserDataSample: IUserData[] = [
    {
        id: 'm5gr84i9',
        status: 'success',
        email: 'ken99@example.com',
        username: 'ken',
        role: 'admin',
    },
    {
        id: '3u1reuv4',
        status: 'success',
        email: 'Abe45@example.com',
        username: 'abe',
        role: 'admin',
    },
    {
        id: 'derv1ws0',
        status: 'processing',
        email: 'Monserrat44@example.com',
        username: 'mon',
        role: 'admin',
    },
    {
        id: 'm5gr84i9',
        status: 'success',
        email: 'ken99@example.com',
        username: 'ken',
        role: 'admin',
    },
    {
        id: '3u1reuv4',
        status: 'success',
        email: 'Abe45@example.com',
        username: 'abe',
        role: 'admin',
    },
    {
        id: 'derv1ws0',
        status: 'processing',
        email: 'Monserrat44@example.com',
        username: 'mon',
        role: 'admin',
    },
    {
        id: 'm5gr84i9',
        status: 'success',
        email: 'ken99@example.com',
        username: 'ken',
        role: 'admin',
    },
    {
        id: '3u1reuv4',
        status: 'success',
        email: 'Abe45@example.com',
        username: 'abe',
        role: 'admin',
    },
    {
        id: 'derv1ws0',
        status: 'processing',
        email: 'Monserrat44@example.com',
        username: 'mon',
        role: 'admin',
    },
    {
        id: 'm5gr84i9',
        status: 'success',
        email: 'ken99@example.com',
        username: 'ken',
        role: 'admin',
    },
    {
        id: '3u1reuv4',
        status: 'success',
        email: 'Abe45@example.com',
        username: 'abe',
        role: 'admin',
    },
    {
        id: 'derv1ws0',
        status: 'processing',
        email: 'Monserrat44@example.com',
        username: 'mon',
        role: 'admin',
    },
    {
        id: 'm5gr84i9',
        status: 'success',
        email: 'ken99@example.com',
        username: 'ken',
        role: 'admin',
    },
    {
        id: '3u1reuv4',
        status: 'success',
        email: 'Abe45@example.com',
        username: 'abe',
        role: 'admin',
    },
    {
        id: 'derv1ws0',
        status: 'processing',
        email: 'Monserrat44@example.com',
        username: 'mon',
        role: 'admin',
    },
];
